//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using WebPortfolio.Core.DataAccess.Abstract;
    
    public partial class UserProfile: IEntity
    {
        public UserProfile()
        {
            this.UserPhones = new HashSet<UserPhone>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserEmail { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string RoutePhoto { get; set; }
    
        public virtual UserAddress UserAddress { get; set; }
        public virtual ICollection<UserPhone> UserPhones { get; set; }
    }
}
