//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public int UserAddressId { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public Nullable<int> Zipcode { get; set; }
        public int UserId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
